### ISSUE TITLE
[Question]Hey Brother! Misspelling name? "aliyun-spirng-boot" or "aliyun-spring-boot"?

### ISSUE THREAD

**Issue by roln** [alibaba/aliyun-spring-boot#10]
Hey Brother! Misspelling name? "aliyun-spirng-boot" or "aliyun-spring-boot"?

**Comment by theonefx** [comment]
> Hey Brother! Misspelling name? "aliyun-spirng-boot" or "aliyun-spring-boot"?

correct, it's a spelling mistake.

**Comment by mercyblitz** [comment]
> Hey Brother! Misspelling name? "aliyun-spirng-boot" or "aliyun-spring-boot"?

Thanks, fixed
