### ISSUE TITLE
[ISSUE] When aliyun-rds-spring-boot-starter is integrated, the application cannot work

### ISSUE THREAD

**Issue by m1ngyuan** [alibaba/aliyun-spring-boot#28]
**Describe the bug**
When aliyun-rds-spring-boot-starter is integrated, the application cannot work

**To Reproduce**

在应用上集成了aliyun-rds-spring-boot-starter后台，应用在启用过程中会抛出duplicate endpoint operations异常，例如：Factory method 'jmxMBeanExporter' threw exception; nested exception is java.lang.IllegalStateException: Unable to map duplicate endpoint operations: [MBean call 'slow'] to rdsSlowEndpoint。
同样的情况发生在RdsErrorEndpoint、RdsPerformanceEndpoint、RdsSlowEndpoint,
为了能正常工作，我认为在这三个类中，只需要对方法进行重命名即可

Aliyun RDS spring boot starter background is integrated in the application. During the application enabling process, duplicate endpoint operations exception will be thrown, such as factory method 'jmxmbeanexport' thread exception; nested exception is java.lang.illegalstateexception: unable to map duplicate endpoint operations: [MBean call 'slow'] to rdsslowendpoint.
The same situation occurs in rdserrorendpoint, rdspermanceendpoint, rdsslowendpoint

In order to work properly, I think in these three classes, but the method needs to be renamed

**Expected behavior**

RDS健康指标能正常输出

RDS health indicators can be output normally

**Comment by m1ngyuan** [comment]
I provide a PR to fix it, #31

**Comment by theonefx** [comment]
which sprint boot version you are using?

**Comment by m1ngyuan** [comment]
> which sprint boot version you are using?
Problems in spring boot 2.2.5 and 2.2.6 also exist

**Comment by m1ngyuan** [comment]
@mercyblitz Please pay attention to this problem. Thank you.
