### ISSUE TITLE
Dependencies confict in OSS

### ISSUE THREAD

**Issue by cmygit** [alibaba/aliyun-spring-boot#35]
**Describe the bug**
![image](https://user-images.githubusercontent.com/29950541/83318778-8a5ff900-a26a-11ea-8664-f76483d1867c.png)

![image](https://user-images.githubusercontent.com/29950541/83318832-f7738e80-a26a-11ea-99c4-df9f980138bb.png)

![image](https://user-images.githubusercontent.com/29950541/83318843-1f62f200-a26b-11ea-8a3b-1dd5730330be.png)

![image](https://user-images.githubusercontent.com/29950541/83318881-8680a680-a26b-11ea-9584-d74202b8b05b.png)

### **But "aliyun-sdk-oss-3.1.0" is rely on "aliyun-java-sdk-core-3.4.0"**

![image](https://user-images.githubusercontent.com/29950541/83318944-40781280-a26c-11ea-844a-aa95d3023215.png)

![image](https://user-images.githubusercontent.com/29950541/83318997-ca27e000-a26c-11ea-8e65-ffa90a17ca13.png)

**Comment by ms-xiaosnow** [comment]
see #40 , you cloud execlue the incompatible version using <execlusions> tag

**Comment by theonefx** [comment]
try move <dependencyManagement/> to parent module:
![image](https://user-images.githubusercontent.com/3760138/91715314-f894be80-ebbf-11ea-86aa-15025ae4e7b0.png)

**Comment by theonefx** [comment]
There is the dependency tree:

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] demo                                                               [pom]
[INFO] common-module                                                      [jar]
[INFO] m1-sub-module                                                      [jar]
[INFO] 
[INFO] --------------------------< com.example:demo >--------------------------
[INFO] Building demo 0.0.1-SNAPSHOT                                       [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ demo ---
[INFO] com.example:demo:pom:0.0.1-SNAPSHOT
[INFO] 
[INFO] ---------------------< com.example:common-module >----------------------
[INFO] Building common-module 0.0.1-SNAPSHOT                              [2/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ common-module ---
[INFO] com.example:common-module:jar:0.0.1-SNAPSHOT
[INFO] \- com.alibaba.cloud:aliyun-oss-spring-boot-starter:jar:1.0.0:compile
[INFO]    +- com.alibaba.cloud:aliyun-context-spring-boot-starter:jar:1.0.0:compile
[INFO]    |  +- com.alibaba.cloud:alicloud-context:jar:1.0.5:compile
[INFO]    |  \- com.aliyun:aliyun-java-sdk-edas:jar:2.44.0:compile
[INFO]    |     \- com.google.code.gson:gson:jar:2.8.6:compile
[INFO]    \- com.aliyun.oss:aliyun-sdk-oss:jar:3.1.0:compile
[INFO]       +- org.apache.httpcomponents:httpclient:jar:4.5.12:compile
[INFO]       |  +- org.apache.httpcomponents:httpcore:jar:4.4.13:compile
[INFO]       |  \- commons-codec:commons-codec:jar:1.14:compile
[INFO]       +- org.jdom:jdom:jar:1.1:compile
[INFO]       +- com.sun.jersey:jersey-json:jar:1.9:compile
[INFO]       |  +- org.codehaus.jettison:jettison:jar:1.1:compile
[INFO]       |  |  \- stax:stax-api:jar:1.0.1:compile
[INFO]       |  +- com.sun.xml.bind:jaxb-impl:jar:2.2.3-1:compile
[INFO]       |  +- org.codehaus.jackson:jackson-core-asl:jar:1.8.3:compile
[INFO]       |  +- org.codehaus.jackson:jackson-mapper-asl:jar:1.8.3:compile
[INFO]       |  +- org.codehaus.jackson:jackson-jaxrs:jar:1.8.3:compile
[INFO]       |  +- org.codehaus.jackson:jackson-xc:jar:1.8.3:compile
[INFO]       |  \- com.sun.jersey:jersey-core:jar:1.9:compile
[INFO]       +- com.aliyun:aliyun-java-sdk-core:jar:4.5.0:compile
[INFO]       |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO]       |  +- javax.xml.bind:jaxb-api:jar:2.3.1:compile
[INFO]       |  |  \- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO]       |  +- org.jacoco:org.jacoco.agent:jar:runtime:0.8.5:compile
[INFO]       |  +- org.ini4j:ini4j:jar:0.5.4:compile
[INFO]       |  +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO]       |  +- io.opentracing:opentracing-api:jar:0.33.0:compile
[INFO]       |  \- io.opentracing:opentracing-util:jar:0.33.0:compile
[INFO]       |     \- io.opentracing:opentracing-noop:jar:0.33.0:compile
[INFO]       +- com.aliyun:aliyun-java-sdk-ram:jar:3.0.0:compile
[INFO]       +- com.aliyun:aliyun-java-sdk-sts:jar:3.0.0:compile
[INFO]       \- com.aliyun:aliyun-java-sdk-ecs:jar:4.2.0:compile
[INFO] 
[INFO] ---------------------< com.example:m1-sub-module >----------------------
[INFO] Building m1-sub-module 0.0.1-SNAPSHOT                              [3/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ m1-sub-module ---
[INFO] com.example:m1-sub-module:jar:0.0.1-SNAPSHOT
[INFO] \- com.example:common-module:jar:0.0.1-SNAPSHOT:compile
[INFO]    \- com.alibaba.cloud:aliyun-oss-spring-boot-starter:jar:1.0.0:compile
[INFO]       +- com.alibaba.cloud:aliyun-context-spring-boot-starter:jar:1.0.0:compile
[INFO]       |  +- com.alibaba.cloud:alicloud-context:jar:1.0.5:compile
[INFO]       |  \- com.aliyun:aliyun-java-sdk-edas:jar:2.44.0:compile
[INFO]       |     \- com.google.code.gson:gson:jar:2.8.6:compile
[INFO]       \- com.aliyun.oss:aliyun-sdk-oss:jar:3.1.0:compile
[INFO]          +- org.apache.httpcomponents:httpclient:jar:4.5.12:compile
[INFO]          |  +- org.apache.httpcomponents:httpcore:jar:4.4.13:compile
[INFO]          |  \- commons-codec:commons-codec:jar:1.14:compile
[INFO]          +- org.jdom:jdom:jar:1.1:compile
[INFO]          +- com.sun.jersey:jersey-json:jar:1.9:compile
[INFO]          |  +- org.codehaus.jettison:jettison:jar:1.1:compile
[INFO]          |  |  \- stax:stax-api:jar:1.0.1:compile
[INFO]          |  +- com.sun.xml.bind:jaxb-impl:jar:2.2.3-1:compile
[INFO]          |  +- org.codehaus.jackson:jackson-core-asl:jar:1.8.3:compile
[INFO]          |  +- org.codehaus.jackson:jackson-mapper-asl:jar:1.8.3:compile
[INFO]          |  +- org.codehaus.jackson:jackson-jaxrs:jar:1.8.3:compile
[INFO]          |  +- org.codehaus.jackson:jackson-xc:jar:1.8.3:compile
[INFO]          |  \- com.sun.jersey:jersey-core:jar:1.9:compile
[INFO]          +- com.aliyun:aliyun-java-sdk-core:jar:4.5.0:compile
[INFO]          |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO]          |  +- javax.xml.bind:jaxb-api:jar:2.3.1:compile
[INFO]          |  |  \- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO]          |  +- org.jacoco:org.jacoco.agent:jar:runtime:0.8.5:compile
[INFO]          |  +- org.ini4j:ini4j:jar:0.5.4:compile
[INFO]          |  +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO]          |  +- io.opentracing:opentracing-api:jar:0.33.0:compile
[INFO]          |  \- io.opentracing:opentracing-util:jar:0.33.0:compile
[INFO]          |     \- io.opentracing:opentracing-noop:jar:0.33.0:compile
[INFO]          +- com.aliyun:aliyun-java-sdk-ram:jar:3.0.0:compile
[INFO]          +- com.aliyun:aliyun-java-sdk-sts:jar:3.0.0:compile
[INFO]          \- com.aliyun:aliyun-java-sdk-ecs:jar:4.2.0:compile
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for demo 0.0.1-SNAPSHOT:
[INFO] 
[INFO] demo ............................................... SUCCESS [  0.691 s]
[INFO] common-module ...................................... SUCCESS [  0.218 s]
[INFO] m1-sub-module ...................................... SUCCESS [  0.063 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.297 s
[INFO] Finished at: 2020-08-31T19:25:37+08:00
[INFO] ------------------------------------------------------------------------
