### ISSUE TITLE
阿里云OSS对象存储依赖引入失败 怎么解决

### ISSUE THREAD

**Issue by wulangg** [alibaba/aliyun-spring-boot#40]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Describe what problem you have encountered**
A clear and concise description of what you want to do.

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

**Comment by c297186864** [comment]
<dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2.2.1.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
</dependency>



Cannot resolve com.alibaba.cloud:aliyun-oss-spring-boot-starter:unknown

**Comment by ms-xiaosnow** [comment]
cause：
1. spring-cloud-alibaba-dependencies 2.2.1.RELEASE pom didn't specify any version of "aliyun-oss-spring-boot-starter"
2. "aliyun-oss-spring-boot-starter" use an  incompatible version of "aliyun-java-sdk-core"

To fix this issue you could change your dependence as beload: 
<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>aliyun-oss-spring-boot-starter</artifactId>
            <version>1.0.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.aliyun</groupId>
                    <artifactId>aliyun-java-sdk-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.aliyun</groupId>
            <artifactId>aliyun-java-sdk-core</artifactId>
            <version>4.5.7</version>
        </dependency>

中文：
这玩意有坑，而且坑贼大，导致问题的主要原因：
1. spring-cloud-alibaba的pom中没有声明指定的 aliyun-oss-spring-boot-starter 版本
2. 指定了上述的版本之后，程序运行会报NoSuchMethodError (一看就想到了jar冲突的问题)，找了一会才发现，starter中引入的alicloud-context与aliyun-java-sdk-core不兼容（(lll￢ω￢)，浪费了我1800s的生命）

解决方案，升级aliyun-java-sdk-core版本就好了，具体操作如下：
1. 引入starter依赖的时候里边加上一个exclusions标签，把aliyun-java-sdk-core依赖排除掉
2. 自己手动引入最新版本的aliyun-java-sdk-core依赖

按照上面的操作应该就万事大吉了，也不晓得后续还会不会有坑（此处严重怀疑程序猿没有测试过就把包发布到中央仓库。。。）

**Comment by theonefx** [comment]
please use "aliyun-spring-boot-dependencies" replace of "spring-cloud-alibaba-dependencies" while import "aliyun-oss-spring-boot-starter"

**Comment by slience-me** [comment]
问题确实很大，在谷粒商城项目遇到
