### ISSUE TITLE
Cannot resolve com.alibaba.cloud:aliyun-oss-spring-boot-starter:unknown

### ISSUE THREAD

**Issue by c297186864** [alibaba/aliyun-spring-boot#41]

**Comment by c297186864** [comment]
![image](https://user-images.githubusercontent.com/4927516/91017875-61f55a00-e621-11ea-8327-ebd508d1c1a5.png)

**Comment by ms-xiaosnow** [comment]
see #40

**Comment by theonefx** [comment]
please use "aliyun-spring-boot-dependencies" replace of "spring-cloud-alibaba-dependencies" while import "aliyun-oss-spring-boot-starter"
