### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by LiuPengGitHubAccount** [alibaba/aliyun-spring-boot#43]
注入的时候报了空指针，有遇到相同问题的么

**Comment by theonefx** [comment]
can you provide more infomation? such as exception stack

**Comment by GeminiCCCC** [comment]
I have the exact same issue.

**Comment by theonefx** [comment]
please provide the exception stacks

**Comment by fangjian0423** [comment]
Closing this issue due to no more information.
