### ISSUE TITLE
maven dependency cannot resolve

### ISSUE THREAD

**Issue by mans8** [alibaba/aliyun-spring-boot#45]
Cannot resolve com.alibaba.cloud:spring-cloud-starter-alicloud-oss.

**Comment by wangyanyi66** [comment]
I have the exact same issue.

Cannot resolve com.alibaba.cloud:aliyun-oss-spring-boot-starter:unknown

**Comment by ppzzyy11** [comment]
![image](https://user-images.githubusercontent.com/20295482/105984064-968ba700-60d4-11eb-9b71-715c5699c2d4.png)
aliyun-oss-spring-boot-starter rather than spring-cloud-starter-alicloud-oss.
