### ISSUE TITLE
[Question]Cannot resolve com.alibaba.cloud:aliyun-oss-spring-boot-starter:unknown

### ISSUE THREAD

**Issue by MCCEYAS** [alibaba/aliyun-spring-boot#63]
<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>aliyun-oss-spring-boot-starter</artifactId>
		</dependency>
<spring-cloud-alibaba.version>2.2.6.RELEASE</spring-cloud-alibaba.version>
           <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

**Comment by WeLinkOn** [comment]
You should add another `Aliyun Spring Boot BOM` in your spring-cloud-alibaba project pom.xml, reference here: [Spring Cloud Alibaba](https://spring.io/projects/spring-cloud-alibaba#overview)

><dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>aliyun-spring-boot-dependencies</artifactId>
    <version>1.0.0</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
