### ISSUE TITLE
[Question] spring-cloud-starter-alicloud-sms 与aliyun-oss-spring-boot-starter 之间的区别

### ISSUE THREAD

**Issue by iPisces77** [alibaba/aliyun-spring-boot#68]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Describe what problem you have encountered**
A clear and concise description of what you want to do.

**Describe what information you have read**
eg. I have read the reference doc of Sentinel

spring-cloud-starter-alicloud-sms and aliyun-oss-spring-boot-starter I see that both are AliBaBa's starter and the functionality between the two is similar, so what is the difference between these two dependencies?

**Comment by steverao** [comment]
They are two different services in Alibaba Cloud, one is [OSS](https://www.aliyun.com/product/oss), another is [SMS](https://www.aliyun.com/product/sms).

**Comment by iPisces77** [comment]
Oh, that's my mistake I was actually asking about the difference between spring-cloud-starter-alicloud-sms and aliyun-sms-spring-boot-starter, sorry

**Comment by fangjian0423** [comment]
It's a history problem, refer https://github.com/alibaba/aliyun-spring-boot/issues/1 . 

The `spring-cloud-starter-alicloud-xxx` artifactId would not be released in future. Let's use the new artifactId `aliyun-xxx-spring-boot-starter`.
